version: 2.1

jobs:
  build:
    macos:
      xcode: 15.4.0
    steps:
      - checkout
      - run:
          name: Install Dart
          command: |
            brew tap dart-lang/dart
            brew install dart
      - run:
          name: Run Unit Tests
          command: |
            dart pub get
            dart test

workflows:
  
  build_and_test:
    jobs:
      - build
