version: 2.1

jobs:
  test:
    macos:
      xcode: 15.4.0
    steps:
      - checkout
      - run:
          name: Install Dart
          command: |
            brew tap dart-lang/dart
            brew install dart
      - run:
          name: Run Unit Tests
          command: |
            dart test

workflows:
  version: 2
  test_build:
    jobs:
      - test
